### ISSUE TITLE
Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by Globegitter** [phonegap/connect-phonegap#126]
I am using cordova to build our web app and trying to debug it using the wonderful phonegap developer app. The app is building and the server via `phonegap serve` running fine. But when trying to connect to it the app crashes and I am getting the following error:

```sh
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:691:11)
    at ServerResponse.res.setHeader (/home/mpadourek/npm/lib/node_modules/phonegap/node_modules/connect-phonegap/node_modules/connect/lib/patch.js:63:22)
    at ServerResponse.<anonymous> (/home/mpadourek/npm/lib/node_modules/phonegap/node_modules/connect-phonegap/node_modules/connect/lib/patch.js:80:14)
    at Array.forEach (native)
    at ServerResponse.res.writeHead (/home/mpadourek/npm/lib/node_modules/phonegap/node_modules/connect-phonegap/node_modules/connect/lib/patch.js:79:28)
    at null.<anonymous> (/home/mpadourek/npm/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:70:21)
    at EventEmitter.emit (events.js:117:20)
    at Archiver.append (/home/mpadourek/npm/lib/node_modules/phonegap/node_modules/connect-phonegap/node_modules/archiver/lib/core.js:317:10)
    at EventEmitter.<anonymous> (/home/mpadourek/npm/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:89:29)
    at EventEmitter.emit (events.js:106:17)
```

Using phonegap `v5.1.1` and running app version `v1.5.4` on Android 5.1.

**Comment by timkim** [comment]
Oh looks like this was left open and should be closed.
