### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by zeke** [phonegap/connect-phonegap#173]
Running the latest phonegap CLI on latest node on OS X, I see this in my server logs:

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at Object.handle (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/cordova/cordova_plugins.js:18:33)
    at next (/usr/local/lib/node_modules/phonegap/node_modules/connect/lib/proto.js:193:15)
    at Object.handle (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/cordova/cordova.js:33:13)
    at next (/usr/local/lib/node_modules/phonegap/node_modules/connect/lib/proto.js:193:15)
    at resume (/usr/local/lib/node_modules/phonegap/node_modules/connect/lib/middleware/static.js:65:7)
    at SendStream.error (/usr/local/lib/node_modules/phonegap/node_modules/connect/lib/middleware/static.js:80:37)
    at emitOne (events.js:96:13)
    at SendStream.emit (events.js:188:7)
```

```
$ phonegap -v
6.3.0

$ node -v
v6.4.0
```

**Comment by surajpindoria** [comment]
Hi @zeke,

I have noticed this every once in awhile but haven't found the proper repro steps. Can you give a few details as to how you came about this error?

**Comment by zeke** [comment]
I'm on OS X, node 6.4.0, phonegap 6.3.0

I installed the PhoneGap desktop app, created a new project with it, ran the server from the desktop app, tried to connect with the iOS app, failed a few times, then decided to try running the server with the CLI instead. That didn't work either, but quitting the iOS app and restarting it seemed to do the trick.

I made no modifications to the generated project before running the server.

Hope that helps. Let me know if you need more info.

**Comment by filmaj** [comment]
I can reproduce this every time with the latest phonegap-cli, _as long as the project you are creating does not include plugins_. Thus why the stack trace points to `cordova-plugins.js` middleware causing this error:

```
Object.handle (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/cordova/cordova_plugins.js:18:33)
```

Repro steps - the key is to provide the blank template (so you get no cordova plugins):

```
$ phonegap create pathtest --template blank
$ cd pathtest
$ phonegap -d serve
$ # wait until the serve is listening, then load up the URL in your browser
```
